import type { ArchiveEntry, DevlogPost, ProjectTask } from "./types";

export const project = {
  title: "VEO ZAVOD",
  subtitle: "An archive of a place learning to remember you",
  chapter: "PRE-PRODUCTION // WINTER BUILD",
  completion: 38,
  build: "0.4.7",
};

export const archiveEntries: ArchiveEntry[] = [
  {
    slug: "branimir-vukelic",
    type: "character",
    title: "Branimir Vukelić",
    eyebrow: "CHARACTER // P-04",
    summary: "The last technician at a transmitter everyone claims is automated.",
    description: [
      "Branimir has kept Radio Glas Prudine alive through four directors, two privatizations and a winter in which nobody paid the electricity bill. He knows which switches are decorative and which lies keep the town calm.",
      "He does not guard a secret because it is valuable. He guards it because admitting the truth would turn thirty years of obedience into a choice.",
    ],
    image: "/images/branimir.png",
    status: "canon",
    progress: 72,
    tags: ["radio", "municipal", "witness", "winter"],
    connections: ["The Repeater", "Radio Glas Prudine", "Water sample 04"],
    updated: "11 JUL 2026",
    quote: "A signal is not the same thing as a voice. People forget that first.",
    facts: [
      { label: "Age", value: "58" },
      { label: "Occupation", value: "Radio technician" },
      { label: "Need", value: "To remain useful" },
      { label: "Contradiction", value: "Repairs what he refuses to hear" },
    ],
  },
  {
    slug: "motel-bijeli-jelen",
    type: "location",
    title: "Motel Bijeli Jelen",
    eyebrow: "LOCATION // L-07",
    summary: "Fourteen rooms, eleven keys and one guest who never checks out on paper.",
    description: [
      "The Bijeli Jelen survives on drivers who miss the last turn before snow closes the road. Its hot water works by rumor. Every room has the same landscape print, hung at a slightly different height.",
      "The player arrives here for shelter and discovers a place organized around being passed through. Nothing is hidden. Nobody has ever looked long enough.",
    ],
    image: "/images/motel-bijeli-jelen.png",
    status: "canon",
    progress: 61,
    tags: ["motel", "hub", "night", "road"],
    connections: ["Room 12", "Marija", "Last bus from Zagreb"],
    updated: "10 JUL 2026",
    quote: "Reception closes when the road does. The road closes when we say it does.",
    facts: [
      { label: "Built", value: "1978" },
      { label: "Rooms", value: "14 / 11 keys" },
      { label: "Gameplay", value: "Social hub + save room" },
      { label: "Weather state", value: "Sleet / blackout" },
    ],
  },
  {
    slug: "water-sample-04",
    type: "item",
    title: "Water Sample 04",
    eyebrow: "EVIDENCE // I-13",
    summary: "Collected downstream. Logged upstream. The dates agree too perfectly.",
    description: [
      "A cloudy sample taken from a kitchen tap in Old Prudina. The municipal label records a source point twelve kilometres away and forty minutes before the player collected it.",
      "It can be surrendered, hidden or poured away. None of those actions proves what was in the bottle. Each proves something about the person holding it.",
    ],
    image: "/images/municipal-evidence.png",
    status: "canon",
    progress: 88,
    tags: ["evidence", "water", "choice", "inventory"],
    connections: ["Municipal laboratory", "Deni", "Mission: Clear enough"],
    updated: "09 JUL 2026",
    facts: [
      { label: "Type", value: "Quest evidence" },
      { label: "Condition", value: "Unsealed" },
      { label: "Branch count", value: "3" },
      { label: "Verified", value: "No" },
    ],
  },
  {
    slug: "clear-enough",
    type: "mission",
    title: "Clear Enough",
    eyebrow: "MISSION // M-03",
    summary: "Carry a bottle across town without deciding what it means too early.",
    description: [
      "The task begins as an errand for a young doctor and becomes a tour of everyone who benefits from uncertainty. The bottle never changes. Its meaning does, six times.",
      "There is no morality meter. Characters remember who was allowed to see the sample, what the player called it, and whether the cap was still sealed.",
    ],
    image: "/images/prudina-bus-stop.png",
    status: "draft",
    progress: 44,
    tags: ["quest", "branching", "doctor", "town"],
    connections: ["Water Sample 04", "Young doctor", "Radio Glas Prudine"],
    updated: "08 JUL 2026",
    facts: [
      { label: "Act", value: "I" },
      { label: "Duration", value: "35–50 min" },
      { label: "States", value: "18 tracked" },
      { label: "Combat", value: "None" },
    ],
  },
  {
    slug: "radio-glas-prudine",
    type: "faction",
    title: "Radio Glas Prudine",
    eyebrow: "INSTITUTION // F-02",
    summary: "Local weather, missing dogs and the official version of yesterday.",
    description: [
      "The station broadcasts traffic, obituaries, folk requests and notices written by offices that no longer have staff. Its authority comes from repetition, not reach.",
      "Between songs, the player can hear consequences arrive before the people responsible know what they have done.",
    ],
    image: "/images/branimir.png",
    status: "draft",
    progress: 53,
    tags: ["radio", "institution", "broadcast", "consequence"],
    connections: ["Branimir Vukelić", "The Repeater", "Daily bulletin"],
    updated: "07 JUL 2026",
    facts: [
      { label: "Frequency", value: "97.4 FM" },
      { label: "Reach", value: "Unreliable" },
      { label: "Staff", value: "3" },
      { label: "Role", value: "Reactive narration" },
    ],
  },
  {
    slug: "repeater-field-note",
    type: "note",
    title: "The Repeater Does Not Hum",
    eyebrow: "FIELD NOTE // N-19",
    summary: "A sound design rule written after three failed ambience passes.",
    description: [
      "Machines in VEO ZAVOD never produce a generic horror drone. Every mechanical sound must imply a comprehensible process: a fan bearing, a contactor, a loose panel, current under load.",
      "Fear comes from recognizing the function and then hearing it continue after the function should have ended.",
    ],
    image: "/images/motel-bijeli-jelen.png",
    status: "canon",
    progress: 100,
    tags: ["audio", "rule", "repeater", "design"],
    connections: ["The Repeater", "Branimir Vukelić", "Audio bible"],
    updated: "06 JUL 2026",
    facts: [
      { label: "Discipline", value: "Sound design" },
      { label: "Rule", value: "Source before mood" },
      { label: "Status", value: "Locked" },
      { label: "Exception", value: "None yet" },
    ],
  },
  {
    slug: "the-returner",
    type: "character",
    title: "The Returner",
    eyebrow: "PLAYABLE CHARACTER // P-01",
    summary: "He came home for a burial and packed as if grief had a return ticket.",
    description: [
      "The player begins after the funeral, not before it. The family has already performed its public grief and dispersed into warm cars. He remains with one red overnight bag, a father who will not answer and a bus route suspended by weather.",
      "His crisis is not discovering a secret. It is deciding whether every reason to leave can survive one more night in the place that produced it.",
    ],
    image: "/images/protagonist-funeral.png",
    status: "draft",
    progress: 64,
    tags: ["player", "funeral", "return", "guilt"],
    connections: ["Last bus stop", "Motel Bijeli Jelen", "Father's flat"],
    updated: "13 JUL 2026",
    quote: "I packed for two nights. That was the first lie I told here.",
    facts: [
      { label: "Age", value: "31" },
      { label: "Arrival", value: "After mother's funeral" },
      { label: "Inventory", value: "Red bag / 3 objects" },
      { label: "Crisis", value: "Leaving requires an answer" },
    ],
  },
  {
    slug: "deni",
    type: "character",
    title: "Deni",
    eyebrow: "CHARACTER // P-07",
    summary: "A young doctor with evidence he cannot verify without the people implicated by it.",
    description: [
      "Deni accepted the Prudina placement because temporary work sounded morally clean. Six months later, two households share the same symptoms and two official samples share an impossible timestamp.",
      "He needs the player because reporting through procedure returns the report to Viktor. Bypassing procedure turns a suspicion into an accusation he may not be able to defend.",
    ],
    image: "/images/deni-clinic.png",
    status: "draft",
    progress: 61,
    tags: ["doctor", "clinic", "water", "evidence"],
    connections: ["Water Sample 04", "Old Prudina Clinic", "Viktor"],
    updated: "13 JUL 2026",
    quote: "I need a clean sample. I no longer know what clean means here.",
    facts: [
      { label: "Age", value: "25" },
      { label: "Contract", value: "Temporary placement" },
      { label: "Need", value: "Independent confirmation" },
      { label: "Contradiction", value: "Needs the system he distrusts" },
    ],
  },
  {
    slug: "marija",
    type: "character",
    title: "Marija",
    eyebrow: "CHARACTER // P-09",
    summary: "The motel keeper who remembers every guest and records only the harmless ones.",
    description: [
      "Marija inherited eleven keys, fourteen rooms and the obligation to call privacy a professional virtue. She knows who used the service stairs during the blackout because she was the person who left them unlocked.",
      "Her crisis begins when protecting a guest becomes indistinguishable from protecting what the guest did. Hospitality has rules; consequence does not honor them.",
    ],
    image: "/images/marija-motel.png",
    status: "draft",
    progress: 52,
    tags: ["motel", "keeper", "witness", "blackout"],
    connections: ["Motel Bijeli Jelen", "Room 12", "Transfer floor"],
    updated: "13 JUL 2026",
    quote: "A key proves I let someone in. It does not prove when they left.",
    facts: [
      { label: "Age", value: "48" },
      { label: "Role", value: "Owner / night reception" },
      { label: "Need", value: "Keep the motel neutral" },
      { label: "Contradiction", value: "Neutrality protects one side" },
    ],
  },
  {
    slug: "viktor",
    type: "character",
    title: "Viktor",
    eyebrow: "CHARACTER // P-11",
    summary: "A water inspector whose safest report proves exactly when he knew.",
    description: [
      "Viktor has survived every municipal reorganization by never being the person with final authority. His signatures confirm process, not truth. Sample 04 changes that because the printer log and the field timestamp cannot both be administrative mistakes.",
      "He is not trying to destroy evidence. He is trying to make every document accurate in isolation, which is how the complete record becomes a lie.",
    ],
    image: "/images/viktor-inspector.png",
    status: "draft",
    progress: 46,
    tags: ["inspector", "municipal", "report", "liability"],
    connections: ["Deni", "Sublevel Central", "Water Sample 04"],
    updated: "13 JUL 2026",
    quote: "My report says what was tested. It cannot say what nobody asked us to test.",
    facts: [
      { label: "Age", value: "52" },
      { label: "Occupation", value: "Municipal inspector" },
      { label: "Need", value: "Preserve procedural distance" },
      { label: "Contradiction", value: "His caution creates the record" },
    ],
  },
  {
    slug: "old-prudina-clinic",
    type: "location",
    title: "Old Prudina Clinic",
    eyebrow: "LOCATION // L-03",
    summary: "Two exam rooms, one working phone and a laboratory nobody officially operates at night.",
    description: [
      "The clinic occupies the ground floor of a building designed for twice the population Prudina still has. Its unused rooms became storage, then an unofficial laboratory when sending samples to the county began taking too long.",
      "The player first experiences it as a safe, bright institution. Each return removes certainty rather than light: a missing coat, a replaced bottle and a printer that has produced a report before the test ends.",
    ],
    image: "/images/clinic-water-lab.png",
    status: "draft",
    progress: 58,
    tags: ["clinic", "laboratory", "water", "night"],
    connections: ["Deni", "Water Sample 04", "Municipal archive"],
    updated: "13 JUL 2026",
    facts: [
      { label: "Built", value: "1984" },
      { label: "Open rooms", value: "2 / 9" },
      { label: "Gameplay", value: "Evidence + dialogue" },
      { label: "Power", value: "Unstable municipal grid" },
    ],
  },
  {
    slug: "the-repeater",
    type: "location",
    title: "The Repeater",
    eyebrow: "LOCATION // L-12",
    summary: "A restricted relay station that broadcasts farther after its input cable is cut.",
    description: [
      "The tower sits inside a military forest nobody patrols and everyone still calls restricted. Its service hut contains ordinary relays, heating elements and a maintenance tape whose instructions have been sampled by the town radio.",
      "Nothing here is paranormal. The horror is a working system receiving the wrong source with enough authority to overwrite local knowledge.",
    ],
    image: "/images/repeater-forest.png",
    status: "draft",
    progress: 41,
    tags: ["tower", "forest", "radio", "restricted"],
    connections: ["Branimir Vukelić", "Radio Glas Prudine", "Military road"],
    updated: "13 JUL 2026",
    facts: [
      { label: "Elevation", value: "1,184 m" },
      { label: "Access", value: "Service road / footpath" },
      { label: "Gameplay", value: "Navigation + signal puzzle" },
      { label: "Weather", value: "Heavy snow" },
    ],
  },
  {
    slug: "transfer-floor",
    type: "location",
    title: "Transfer Floor",
    eyebrow: "LOCATION // L-16",
    summary: "An empty slaughterhouse route still billed for water it no longer uses.",
    description: [
      "The private slaughterhouse closed after a fire in its administrative wing, but its municipal connection was never removed. The loading floor is empty: rails, plastic curtains, drains and an office cage whose lights come on during town blackouts.",
      "This is not a gore location. Its threat is industrial continuity. The building has stopped producing meat and continues consuming water, power and official silence.",
    ],
    image: "/images/slaughterhouse-loading.png",
    status: "draft",
    progress: 29,
    tags: ["industrial", "slaughterhouse", "water", "contractor"],
    connections: ["Sublevel Central", "Marija", "Service tunnel"],
    updated: "13 JUL 2026",
    facts: [
      { label: "Closed", value: "2018" },
      { label: "Meter status", value: "Active" },
      { label: "Gameplay", value: "Stealth route / evidence" },
      { label: "Combat", value: "Avoidable" },
    ],
  },
  {
    slug: "sublevel-central",
    type: "location",
    title: "Sublevel Central",
    eyebrow: "LOCATION // L-19",
    summary: "The town's oldest machinery is also the only part nobody privatized successfully.",
    description: [
      "Beneath Prudina, three generations of pumps occupy one continuous concrete chamber. New pipes cross old reservoirs without sharing diagrams. Maintenance workers navigate by remembered sound because several platform numbers refer to structures that were demolished above ground.",
      "The central is not a final dungeon. It is proof that every institution on the surface depends on people quietly keeping an incoherent system alive.",
    ],
    image: "/images/underground-pumping.png",
    status: "draft",
    progress: 22,
    tags: ["underground", "pumps", "infrastructure", "water"],
    connections: ["Viktor", "Transfer Floor", "Old intake"],
    updated: "13 JUL 2026",
    facts: [
      { label: "Depth", value: "38 m" },
      { label: "Active pumps", value: "4 / 7" },
      { label: "Gameplay", value: "Traversal + system state" },
      { label: "Status", value: "Scale blockout" },
    ],
  },
];

export const devlogs: DevlogPost[] = [
  {
    slug: "corridor-changes-when-unseen",
    number: "LOG 032",
    title: "The corridor only changes when you look away",
    dek: "A tiny room-state system made the motel frightening without spawning a single enemy.",
    date: "13 JUL 2026",
    readTime: "8 MIN",
    category: "SURVIVAL HORROR",
    image: "/images/motel-bijeli-jelen.png",
    imageAlt: "A low-poly motel corridor disappearing into darkness",
    captureLabel: "PROTOTYPE CAPTURE / MOTEL LOOP B",
    status: "implemented",
    build: "0.4.8",
    facts: [
      { label: "ROOM STATES", value: "4" },
      { label: "NEW ENEMIES", value: "0" },
      { label: "TEST ROUTE", value: "06:40" },
      { label: "STATUS", value: "IN BUILD" },
    ],
    gallery: [
      { src: "/images/motel-bijeli-jelen.png", alt: "Motel exterior in freezing rain", caption: "The motel before the loop begins. The same lobby remains visible through the glass after its interior state has changed.", label: "01 / EXTERIOR" },
      { src: "/images/municipal-evidence.png", alt: "Municipal evidence on a worn desk", caption: "The receipt is the state trigger. Picking it up is ordinary; returning through the corridor is not.", label: "02 / TRIGGER" },
      { src: "/images/radio-control-room.png", alt: "Dark analogue control room lit by an emergency lamp", caption: "Lighting language for the final corridor state: one practical source, no supernatural glow.", label: "03 / LIGHT STUDY" },
      { src: "/images/marija-motel.png", alt: "Marija behind motel reception during a blackout", caption: "Marija witnesses the loop without confirming it. Her reception state changes only after the player asks for the wrong key.", label: "04 / WITNESS" },
    ],
    body: [
      {
        paragraphs: [
          "The first motel prototype tried to frighten the player with an event at the end of a hallway. It worked once and then became a delivery route: walk forward, receive scare, continue. The revision treats the hallway as memory instead. It records what the player has seen, which door they used and whether they turned around voluntarily.",
          "Nothing changes while the corridor is on camera. Leave through the stairwell, collect the municipal receipt and return: the vending machine has moved half a metre, Room 12 is now numbered 11, and the carpet seam points toward a door that was previously locked. Each edit is mundane enough to question.",
        ],
      },
      {
        heading: "The rule is smaller than the effect",
        paragraphs: [
          "The room does not need procedural horror. It needs four authored states and a strict transition rule: never mutate visible geometry. A change queues while the player is present, then applies only after every active camera has lost the affected room.",
          "That restriction keeps the trick fair. A careful player can build a mental map, notice the contradiction and choose whether to test it again. Horror arrives from the player's own verification loop.",
        ],
      },
      {
        heading: "What is still wrong",
        paragraphs: [
          "The third state currently reads too clearly because the red exit sign changes at the same time as the room number. The next pass will remove one clue and measure whether testers still stop without being told why.",
        ],
      },
    ],
    code: {
      filename: "corridor_memory.gd",
      language: "GDScript",
      snippet: "func request_state(next_state: int) -> void:\n    pending_state = next_state\n    if not visibility_tracker.is_room_visible(room_id):\n        apply_pending_state()\n\nfunc _on_room_became_hidden(hidden_id: StringName) -> void:\n    if hidden_id == room_id and pending_state > current_state:\n        apply_pending_state()",
    },
    tryIt: [
      "Walk from reception to Room 12 without turning around.",
      "Collect the receipt, return through the stairwell and name the first change you notice.",
      "Repeat the route while looking backward; no geometry should pop while visible.",
    ],
  },
  {
    slug: "fixed-cameras-without-stolen-control",
    number: "LOG 031",
    title: "Fixed cameras that never steal control",
    dek: "The camera can cut like a film edit while movement remains predictable under the player's thumb.",
    date: "12 JUL 2026",
    readTime: "7 MIN",
    category: "CAMERA",
    image: "/images/prudina-night-watch.png",
    imageAlt: "A solitary figure waiting at a snowy municipal bus stop beneath a radio tower",
    captureLabel: "CONCEPT CAPTURE / CAMERA C-14",
    status: "prototype",
    build: "0.4.8",
    facts: [
      { label: "CAMERAS", value: "17" },
      { label: "INPUT MODE", value: "WORLD" },
      { label: "BLEND", value: "0.18 S" },
      { label: "STATUS", value: "TESTING" },
    ],
    gallery: [
      { src: "/images/prudina-night-watch.png", alt: "High fixed-camera view of a snowbound bus station", caption: "Camera C-14 holds the shelter low in frame and lets the empty road become the threat. Original concept capture; not final gameplay.", label: "01 / C-14" },
      { src: "/images/prudina-bus-stop.png", alt: "Wide winter view of the Prudina bus stop", caption: "The earlier eye-level composition explained the location, but it made every exit equally safe.", label: "02 / OLD ANGLE" },
      { src: "/images/motel-bijeli-jelen.png", alt: "Motel exterior framed through winter weather", caption: "Exterior cameras share the same forward vector across cuts, so holding a direction never reverses the character.", label: "03 / CONTINUITY" },
    ],
    body: [
      {
        paragraphs: [
          "Fixed cameras give every room a point of view, but they can also turn walking through a doorway into a fight with the controller. The prototype now separates presentation direction from movement direction. The camera may cut 140 degrees; the character continues along the same world-space vector until the stick returns to neutral.",
          "That one latch removed the ugly half-second where a player crosses a camera boundary, keeps holding forward and immediately walks back through it. It also lets the framing become more aggressive without making navigation feel antique for the wrong reason.",
        ],
      },
      {
        heading: "Cut on commitment, not on contact",
        paragraphs: [
          "Camera volumes overlap. The next camera becomes eligible at the threshold but does not cut until the player has travelled 0.65 metres into its claim. Near a doorway, the old shot therefore survives hesitation and only yields once the movement says the decision is real.",
          "The bus shelter shot shown here is intentionally high and distant. The person is readable; the road is not. That imbalance makes waiting feel like an action.",
        ],
      },
    ],
    code: {
      filename: "fixed_camera_motor.gd",
      language: "GDScript",
      snippet: "if input.length() < DEADZONE:\n    latched_world_direction = Vector3.ZERO\nelif latched_world_direction == Vector3.ZERO:\n    latched_world_direction = camera_basis * Vector3(input.x, 0.0, input.y)\n\nvelocity = latched_world_direction.normalized() * move_speed",
    },
    tryIt: [
      "Hold forward while crossing three camera zones; the character must never reverse.",
      "Stop inside the overlap, release the stick, then choose a new direction using the new camera.",
      "Walk back and forth on the threshold; the camera should not chatter between shots.",
    ],
  },
  {
    slug: "radio-enemy-without-combat-animation",
    number: "LOG 030",
    title: "A radio enemy with no combat animation",
    dek: "The repeater attacks the player's information first: directions, save-room certainty and the sound of a safe route.",
    date: "11 JUL 2026",
    readTime: "6 MIN",
    category: "AUDIO",
    image: "/images/radio-control-room.png",
    imageAlt: "An analogue radio control room under red emergency light",
    captureLabel: "CONCEPT CAPTURE / SIGNAL EVENT R-03",
    status: "testing",
    build: "0.4.8",
    facts: [
      { label: "VOICE LAYERS", value: "3" },
      { label: "COMBAT", value: "NONE" },
      { label: "EVENT RANGE", value: "22 M" },
      { label: "STATUS", value: "GREYBOX" },
    ],
    gallery: [
      { src: "/images/radio-control-room.png", alt: "Low-poly radio station control room with a technician and emergency lamp", caption: "The station after mains power fails. Original concept capture used to lock camera, light and material targets.", label: "01 / CONTROL" },
      { src: "/images/branimir.png", alt: "Portrait of tired radio technician Branimir", caption: "Branimir's recorded maintenance phrases are split into harmless words and rebuilt by the repeater out of order.", label: "02 / VOICE SOURCE" },
      { src: "/images/municipal-evidence.png", alt: "Evidence packet beside an analogue recorder", caption: "Physical evidence stays reliable while the broadcast lies. The player must decide which channel to trust.", label: "03 / COUNTERPOINT" },
      { src: "/images/repeater-forest.png", alt: "Radio repeater tower inside a restricted snowy forest", caption: "The signal chapter leaves the familiar town only when the copied safe-room sound becomes impossible to ignore.", label: "04 / SOURCE" },
    ],
    body: [
      {
        paragraphs: [
          "The repeater is not a creature waiting behind a door. It is a routing system that learns which sounds the player has accepted as safe. The first time a save room is entered, its ventilation fan and fluorescent ballast are recorded as a comfort profile. Later, the repeater can play a damaged version of that profile from an unsafe corridor.",
          "It never creates information from nothing. Every false direction is assembled from a real announcement, maintenance recording or room tone the player has already heard. That makes the deception traceable instead of magical.",
        ],
      },
      {
        heading: "No volume spikes",
        paragraphs: [
          "The event is forbidden from getting louder than the room it occupies. Tension comes from spatial contradiction: a close voice with distant reverb, a fan loop panned behind a wall with no room behind it, or a radio sign-off that begins before the player switches the set on.",
          "The current build still reveals the crossfade on headphones. The next test is not scarier audio; it is a cleaner seam.",
        ],
      },
    ],
    code: {
      filename: "signal_mimic.gd",
      language: "GDScript",
      snippet: "func choose_false_landmark(memory: Array[SoundMemory]) -> SoundMemory:\n    var heard := memory.filter(func(m): return m.times_heard >= 2)\n    heard.sort_custom(func(a, b): return a.safety_score > b.safety_score)\n    return heard.front() if not heard.is_empty() else null",
    },
    tryIt: [
      "Enter the maintenance room twice and learn its fan sound.",
      "Trigger the blackout, then follow the copied fan through the service corridor.",
      "Wear headphones and report the exact moment the imitation becomes obvious.",
    ],
  },
  {
    slug: "inventory-is-part-of-the-room",
    number: "LOG 029",
    title: "The inventory screen is part of the room",
    dek: "Opening a menu should not stop the threat, erase the soundscape or hand the player a neutral place to think.",
    date: "10 JUL 2026",
    readTime: "5 MIN",
    category: "INTERFACE",
    image: "/images/municipal-evidence.png",
    imageAlt: "A cloudy evidence bottle and municipal forms on a worn desk",
    captureLabel: "INTERFACE STUDY / EVIDENCE SLOT",
    status: "prototype",
    build: "0.4.8",
    facts: [
      { label: "SLOTS", value: "8" },
      { label: "PAUSE", value: "PARTIAL" },
      { label: "AUDIO", value: "LIVE" },
      { label: "STATUS", value: "INPUT PASS" },
    ],
    gallery: [
      { src: "/images/municipal-evidence.png", alt: "Municipal evidence laid out under a desk lamp", caption: "Evidence objects are photographed in the light where they were found, keeping the inventory tied to place.", label: "01 / OBJECT" },
      { src: "/images/branimir.png", alt: "Branimir seen through dirty glass", caption: "Character reactions stay audible while the inventory is open. The menu is not a private conversation.", label: "02 / WITNESS" },
      { src: "/images/motel-bijeli-jelen.png", alt: "A motel exterior in darkness", caption: "The room remains dimly visible behind a translucent inspection layer instead of cutting to a separate interface scene.", label: "03 / CONTEXT" },
      { src: "/images/clinic-water-lab.png", alt: "Municipal clinic laboratory under cold fluorescent light", caption: "Sample inspection retains the clinic's live sound and light instead of moving the object into a neutral menu void.", label: "04 / LAB" },
    ],
    body: [
      {
        paragraphs: [
          "The inventory now slows the simulation to twenty percent instead of pausing it. Doors do not suddenly open and enemies do not deal cheap damage, but positional audio, light flicker and scripted voices continue. The player gains time to inspect, not immunity from the room.",
          "Eight slots are enough to create a packing decision without turning every pickup into housekeeping. Evidence, medicine and tools share space; keys do not. A discarded story object remains where it was left and can be recovered unless the world state makes that location inaccessible.",
        ],
      },
      {
        heading: "Make empty space visible",
        paragraphs: [
          "Empty slots are rendered with the faint outline of the last item removed. It is not a hint or a collection counter. It lets the inventory retain a short memory of the player's priorities, which becomes useful when a missing object matters several rooms later.",
        ],
      },
    ],
    tryIt: [
      "Open the inventory beside the motel boiler and listen for whether the room still feels present.",
      "Fill all eight slots, discover medicine and decide what to leave behind.",
      "Return after one state transition and confirm the discarded object still exists.",
    ],
  },
  {
    slug: "first-ten-minutes-broke",
    number: "LOG 028",
    title: "What the first ten minutes actually broke",
    dek: "A short playtest exposed a camera loop, a silent objective and one beautifully useless locked door.",
    date: "09 JUL 2026",
    readTime: "7 MIN",
    category: "PLAYTEST",
    image: "/images/prudina-bus-stop.png",
    imageAlt: "The empty bus stop where the playable route begins",
    captureLabel: "PLAYTEST ROUTE / BUILD 0.4.7",
    status: "testing",
    build: "0.4.7",
    facts: [
      { label: "TESTERS", value: "3" },
      { label: "BLOCKERS", value: "2" },
      { label: "FIXED", value: "4 / 7" },
      { label: "RETEST", value: "PENDING" },
    ],
    gallery: [
      { src: "/images/prudina-bus-stop.png", alt: "Foggy winter bus stop in Prudina", caption: "Start point. Two testers walked toward the decorative road because the playable exit had less contrast.", label: "01 / START" },
      { src: "/images/motel-bijeli-jelen.png", alt: "Motel Bijeli Jelen during sleet", caption: "The motel door worked, but the camera cut made it look locked. That is a presentation bug, not a player mistake.", label: "02 / BLOCKER" },
      { src: "/images/municipal-evidence.png", alt: "Water sample evidence in a dim office", caption: "The sample was picked up by everyone; nobody understood it was the current objective.", label: "03 / OBJECTIVE" },
      { src: "/images/branimir.png", alt: "Radio technician Branimir in a dark workspace", caption: "Branimir's optional line became the only clear direction, so it is no longer optional in the next route.", label: "04 / ROUTING" },
      { src: "/images/protagonist-funeral.png", alt: "Returning protagonist alone after a winter funeral", caption: "The route now begins with the character's crisis visible before the first objective is issued.", label: "05 / OPENING" },
    ],
    body: [
      {
        paragraphs: [
          "The ten-minute route was supposed to prove movement, one conversation, one evidence pickup and the walk to the motel. It proved those systems individually. As a route, it failed twice: the world framed a blocked road as the main path, and the objective update arrived under a radio burst that every tester treated as ambience.",
          "The useful result is not that players need clearer arrows. The scene needs clearer consequences. The playable exit now carries footprints and a wind break; the decorative road continues into undisturbed snow. The objective appears when the bottle returns to the player's hand, not when an unrelated line finishes.",
        ],
      },
      {
        heading: "Keep the beautiful useless door",
        paragraphs: [
          "Every tester tried the chained maintenance door. Removing it would make the route efficient and less believable. It stays, but its failed interaction now teaches the door language used later: handle movement, chain tension, then a short spoken observation only on the first attempt.",
          "The retest succeeds only if nobody asks where to go and at least one person still checks that door. Clarity should not eliminate curiosity.",
        ],
      },
    ],
    tryIt: [
      "Reach the motel without an objective marker or verbal hint from the developer.",
      "Explain the current objective after collecting the bottle.",
      "Name any door you expected to open and what made you expect it.",
    ],
  },
  {
    slug: "making-fog-remember",
    number: "LOG 027",
    title: "Making the fog remember where you have been",
    dek: "A progress system should alter the world before it congratulates the player.",
    date: "11 JUL 2026",
    readTime: "6 MIN",
    category: "SYSTEMS",
    image: "/images/prudina-bus-stop.png",
    imageAlt: "A snowbound bus stop fading into dense fog",
    captureLabel: "PRODUCTION CAPTURE / FOG MEMORY TEST",
    status: "implemented",
    build: "0.4.7",
    facts: [
      { label: "WORLD MARKERS", value: "6" },
      { label: "UI BARS", value: "0" },
      { label: "PERSISTENCE", value: "LOCAL" },
      { label: "STATUS", value: "IN BUILD" },
    ],
    gallery: [
      { src: "/images/prudina-bus-stop.png", alt: "Bus stop and road disappearing into winter fog", caption: "The first landmark is visible only after the streetlight task is completed.", label: "01 / BEFORE" },
      { src: "/images/motel-bijeli-jelen.png", alt: "Motel lights emerging through sleet", caption: "Warm windows replace a progress notification: the completed power task changes the route itself.", label: "02 / AFTER" },
    ],
    body: [
      {
        paragraphs: [
          "Most progress bars describe work after it happens. I wanted the town to do that job instead. A repaired streetlight, a moved chair and a voice on the radio can each become proof that the build changed, even when the player never sees a number.",
          "The website now uses the same idea. Completing a production task restores a signal in the project map. Visitors see a place becoming more legible; I see the ordinary work that made it happen.",
        ],
      },
      {
        heading: "The rule",
        paragraphs: [
          "Every milestone needs one public consequence and one private record. The public consequence tells a story. The private record prevents the story from becoming a lie.",
          "This is why a finished dialogue pass can unlock a new character fragment while the studio keeps the ugly checklist, the rejected lines and the reason the scene was rewritten.",
        ],
      },
    ],
    tryIt: [
      "Complete one street-power task and return to the bus stop.",
      "Find the changed landmark without opening a menu.",
      "Reload the save and confirm the world state persists.",
    ],
  },
  {
    slug: "three-normal-actions",
    number: "LOG 026",
    title: "Three normal actions with heavy consequences",
    dek: "No red choice, no blue choice. Just a bottle, a key and somebody waiting.",
    date: "08 JUL 2026",
    readTime: "4 MIN",
    category: "NARRATIVE",
    image: "/images/municipal-evidence.png",
    imageAlt: "A cloudy water sample and paperwork under a desk lamp",
    captureLabel: "EVIDENCE CAPTURE / SAMPLE 04",
    status: "design-note",
    build: "0.4.7",
    facts: [
      { label: "ACTIONS", value: "3" },
      { label: "BRANCHES", value: "18" },
      { label: "METER", value: "NONE" },
      { label: "STATUS", value: "WRITING" },
    ],
    gallery: [
      { src: "/images/municipal-evidence.png", alt: "Evidence bottle and municipal documentation", caption: "The bottle stays visually ordinary while its social meaning changes between witnesses.", label: "01 / EVIDENCE" },
      { src: "/images/branimir.png", alt: "Branimir watching from a radio workspace", caption: "Who sees the sample matters more than which dialogue option follows.", label: "02 / WITNESS" },
    ],
    body: [
      {
        paragraphs: [
          "The dramatic actions in Prudina are intentionally unimpressive. Deliver a sample. Return a key. Repeat what somebody said. The pressure comes from timing, access and the social cost of being seen doing something ordinary.",
          "A choice becomes heavy when the player understands enough to hesitate but not enough to calculate a correct answer.",
        ],
      },
    ],
    tryIt: [
      "Carry the sample to the clinic without showing it to Branimir.",
      "Repeat and let the station log its label number.",
      "Compare only what characters know; no morality score should appear.",
    ],
  },
  {
    slug: "why-branimir-looks-tired",
    number: "LOG 025",
    title: "Why Branimir looks tired instead of frightening",
    dek: "The most useful character design note this week was to remove the performance.",
    date: "03 JUL 2026",
    readTime: "5 MIN",
    category: "CHARACTERS",
    image: "/images/branimir.png",
    imageAlt: "Branimir, an exhausted radio technician, in a dim municipal room",
    captureLabel: "CHARACTER STUDY / BRANIMIR P-04",
    status: "design-note",
    build: "0.4.6",
    facts: [
      { label: "SILHOUETTES", value: "5" },
      { label: "SELECTED", value: "04" },
      { label: "THREAT POSE", value: "REMOVED" },
      { label: "STATUS", value: "ART PASS" },
    ],
    gallery: [
      { src: "/images/branimir.png", alt: "Character study of Branimir in work clothes", caption: "The selected version looks interrupted at work, not staged as a villain.", label: "01 / SELECTED" },
      { src: "/images/radio-control-room.png", alt: "Branimir standing inside the dark radio control room", caption: "The room carries the threat so the character does not need to perform it.", label: "02 / IN SCENE" },
    ],
    body: [
      {
        paragraphs: [
          "Early versions dressed Branimir as a warning. Strong silhouette, deep shadows, too much certainty. He looked like the plot had already explained him.",
          "Now he is a municipal worker at the end of a shift. The threat, if there is one, lives in what a normal person can normalize over thirty winters.",
        ],
      },
    ],
    tryIt: [
      "Meet Branimir before reading any evidence note.",
      "Describe his job and immediate need without guessing his plot role.",
      "Flag any pose or line that reads as an obvious villain signal.",
    ],
  },
];

export const tasks: ProjectTask[] = [
  { id: "t1", title: "Lock Act I critical path", area: "Writing", state: "active", xp: 80 },
  { id: "t2", title: "Motel lobby lighting pass", area: "Art", state: "done", xp: 40 },
  { id: "t3", title: "Radio consequence event bus", area: "Code", state: "active", xp: 60 },
  { id: "t4", title: "Record winter room tone", area: "Audio", state: "blocked", xp: 35 },
  { id: "t5", title: "Publish July micro-devlog", area: "Community", state: "backlog", xp: 25 },
  { id: "t6", title: "Water sample inventory mesh", area: "Art", state: "done", xp: 45 },
  { id: "t7", title: "Branimir dialogue pass 2", area: "Writing", state: "active", xp: 55 },
];

export function findEntry(slug: string) {
  return archiveEntries.find((entry) => entry.slug === slug);
}

export function findPost(slug: string) {
  return devlogs.find((post) => post.slug === slug);
}
